name: CI/CD Pipeline for EasyInfoDrop

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake libqt5widgets5 libx11-dev cmake build-essential
      - name: Configure build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
      - name: Build
        run: |
          cd build
          make
      - name: Debug build output
        run: |
          ls -l build/EasyInfoDrop
      - uses: actions/upload-artifact@v4
        with:
          name: EasyInfoDrop
          path: build/EasyInfoDrop
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: EasyInfoDrop
          path: release
      - name: Debug file structure
        run: |
          ls -R release
          echo "Checking downloaded artifact:"
          find release -type f
      - name: Create tarball
        run: |
          chmod +x release/EasyInfoDrop
          tar -czvf release/release-easy-info-drop-${{ github.ref_name }}.tar.gz -C release EasyInfoDrop
          echo "Tarball contents:"
          tar -tzvf release/release-easy-info-drop-${{ github.ref_name }}.tar.gz
      - name: Create and upload release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: release/release-easy-info-drop-${{ github.ref_name }}.tar.gz
          body: |
            EasyInfoDrop Release ${{ github.ref_name }}

            To run:
            ```bash
            tar -xzvf release-easy-info-drop-${{ github.ref_name }}.tar.gz
            chmod +x EasyInfoDrop
            ./EasyInfoDrop
            ```

            Includes `config/config.json` for immediate use.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
