name: CI/CD Pipeline for EasyInfoDrop

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qt5-qmake libqt5widgets5 libx11-dev cmake build-essential
      - run: |
          mkdir build
          cd build
          cmake ..
      - run: |
          cd build
          make
      - uses: actions/upload-artifact@v4
        with:
          name: EasyInfoDrop
          path: build/EasyInfoDrop
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: config
          path: config/config.json
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: EasyInfoDrop
          path: release
      - uses: actions/download-artifact@v4
        with:
          name: config
          path: release
      - run: chmod +x release/EasyInfoDrop
      - run: tar -czvf release/EasyInfoDrop-${{ github.ref_name }}-linux.tar.gz -C release EasyInfoDrop config.json
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: true
          prerelease: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/EasyInfoDrop-${{ github.ref_name }}-linux.tar.gz
          asset_name: release-easy-info-drop-v${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
